# [START service]
apiVersion: v1
kind: Service
metadata:
  name: acv-img-proxy
  labels:
    app: acv-img-proxy
spec:
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000
    - name: https
      protocol: TCP
      port: 443
      targetPort: 8000
  selector:
    app: acv-img-proxy-replica-set
# [END service]
