# [START service]
apiVersion: v1
kind: Service
metadata:
  namespace: "development"
  name: acv-img-proxy
  labels:
    app: acv-img-proxy
spec:
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000
  selector:
    app: acv-img-proxy-replica-set
# [END service]
